select * from customer limit 20;

-- What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
with cte as(
select avg(purchase_amount) as average 
from customer
)
select c.customer_id,c.purchase_amount
from customer c,cte 
where c.discount_applied='Yes' and c.purchase_amount>=cte.average

-- Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating)::numeric,2) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Compare the average purchase amounts between Standard and Express shipping.
select shipping_type,round(avg(purchase_amount),2) as avgerage
from customer
where shipping_type='Standard' or shipping_type='Express'
group by shipping_type

-- Do subscribed customers spend more?-No Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(count(case when discount_applied='Yes' then 1 end)*100/count(*),2) as percentage
from customer
group by item_purchased
order by percentage desc
limit 5

select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)*100/count(*),2) as percentage
from customer
group by item_purchased
order by percentage desc
limit 5

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case 
  when previous_purchases=1 then 'New'
  when previous_purchases between 2 and 10 then 'Returning'
  else 'Loyal'
  end as customer_segment
 from customer
)

select customer_segment,count(*) as "Number Of Customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within each category?
with cte as(
select category,item_purchased,count(*) as cnt
from customer
group by category,item_purchased
order by category,cnt desc
)

select category,item_purchased,cnt
from(
select category,item_purchased,cnt,
row_number() over(partition by category order by cnt desc) as rnk
from cte
)
where rnk<=3

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5 
group by subscription_status

-- What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

------------------------
--overall revenue
select sum(purchase_amount) as total_revenue
from customer;



--Top Customers Contribution
with customer_revenue as (
    select customer_id,
           sum(purchase_amount) as total_spend
    from customer
    group by customer_id
),
ranked_customers as (
    select *,
           row_number() over(order by total_spend desc) as rnk,
           count(*) over() as total_customers
    from customer_revenue
),
top_customers as (
    select sum(total_spend) as top_revenue
    from ranked_customers
    where rnk <= total_customers * 0.2
),
overall as (
    select sum(purchase_amount) as total_revenue
    from customer
)
select 
    top_revenue,
    total_revenue,
    round((top_revenue/total_revenue)*100,2) as contribution_percent
from top_customers, overall;

WITH customer_revenue AS (
    SELECT customer_id,
           SUM(purchase_amount) AS total_spent
    FROM customer
    GROUP BY customer_id
),
ranked_customers AS (
    SELECT *,
           PERCENT_RANK() OVER (ORDER BY total_spent DESC) AS pr
    FROM customer_revenue
)
SELECT 
    SUM(total_spent) AS top_20_revenue
FROM ranked_customers
WHERE pr <= 0.20;
